;--------------------------------------------------------------------------
; PETSCII
;--------------------------------------------------------------------------
	STOP	= $03 ; STOP key
	CR	= $0D ; CARRIAGE RETURN
	QUOT	= $22 ; "
	CLRHOME	= $93 ; clear screen
	HOME	= $13 ; home
	CURDN	= $11 ; cursor down
	CURLF	= $9D ; cursor left
	CURRT	= $1D ; cursor right
	RVSON	= $12 ; reverse on
	RVSOFF	= $92 ; reverse off
