; ---------- STATUS -------------------------------------------------------

	ST_TIMEOUT_WR		= 1	; Time out on write
	ST_TIMEOUT_RD		= 2	; Time out on read
	ST_TIMEOUTS		= 3
	ST_EOI			= 64	; Last byte
	ST_NODEV		= 128	; Device not present


; ---------- CBM DOS ERROR CODES ------------------------------------------

	ERROR_OK		= 0
	ERROR_FILE_NOT_FOUND 	= 62
	ERROR_FILE_EXISTS	= 63
	ERROR_ILLEGAL_TS	= 66

; ---------- FLOPPY DISK CONTROLLER ERROR CODES ---------------------------
	FDC_OK			= 1
	

